### PR TITLE
fix spurious logging issue

### PR DESCRIPTION
**Pull request by Zsailer**
This fixes the issue we've been seeing in JupyterLab with spurious logging. 

See @ellisonbg's image originally posted in jupyter/jupyter_server#272. 

image

### CODE REVIEW

**Comment by Zsailer** [comment]
Oops, fixing the tests now. I ran them locally on the wrong branch. sorry for the spam here.

**Comment by Zsailer** [comment]
Ok, fixed!

**Comment by blink1073** [comment]
Thanks!

**Comment by echarles** [comment]
Thx @Zsailer

**Pull request merged**
