### PR TITLE
Fallback to context-less translation on Python 3.7

### PR DESCRIPTION
**Pull request by krassowski**
Fallback to context-less translation on Python 3.7 and fix some typing issues.

Fixes https://github.com/jupyterlab/jupyterlab/issues/11148, based on https://github.com/napari/napari/pull/2305 (added @goanpeca as a co-author).

### CODE REVIEW

**Review by goanpeca — APPROVED** [review]
Thanks for working on this @krassowski 

LGTM!

**Comment by blink1073** [comment]
Thanks!   Starting a release now

**Comment by krassowski** [comment]
Thanks for a quick release! I just confirmed that it works well with the latest release using a new gist with `jupyterlab-server==2.8.2` pin (https://gist.github.com/krassowski/cef3614c3eae6d17f078fe15d88372c3).

**Comment by blink1073** [comment]
Great, thanks for verifying!

**Pull request merged**
