### PR TITLE
PR: Add a translations handler

### PR DESCRIPTION
**Pull request by goanpeca**
Add a translation handler plus the utilities needed to find translations from language packs and the one bundled within packages.

This also correctly merges localization data from packages into the language packs, if the package provides a newer version.

Added tests!

### CODE REVIEW

**Comment by goanpeca** [comment]
@blink1073 @afshin this is ready for review!

**Comment by blink1073** [comment]
Thanks @goanpeca!  I'll review this tomorrow.

**Comment by blink1073** [comment]
https://pypi.org/project/jupyterlab-server/1.3.0rc0/#files

**Comment by goanpeca** [comment]
Awesome :-) Thanks!

**Pull request merged**
