### PR TITLE
PR: Add translation managers for server side translation

### PR DESCRIPTION
**Pull request by goanpeca**

### CODE REVIEW

**Comment by jasongrout** [comment]
We are planning to release JupyterLab next week, which requires a release of jupyterlab_server 2.0. This is the last issue on the 2.0 milestone. What is the status? Can it be bumped, or is it ready to go in, or is it a blocker for 2.0?

**Comment by goanpeca** [comment]
Hi @jasongrout will work on this tonight. Need to add some tests.

**Comment by blink1073** [comment]
I just released 2.0 final.  Since this is additive, it can go in a 2.1 release.

**Comment by goanpeca** [comment]
>I just released 2.0 final. Since this is additive, it can go in a 2.1 release.

Sounds good @blink1073

**Review by blink1073 — APPROVED** [review]
Looks good, thank you!

**Comment by blink1073** [comment]
https://pypi.org/project/jupyterlab-server/2.1.0/

**Pull request merged**
