### PR TITLE
Add util to get consolidated page_config from higher levels

### PR DESCRIPTION
**Pull request by divyansshhh**
Required for jupyterlab/jupyterlab#16102

### CODE REVIEW

**Comment by krassowski** [comment]
The linter is not happy yet:

```
jupyterlab_server/config.py: note: In function "_get_config_manager":
jupyterlab_server/config.py:396: error: "object" has no attribute "__iter__";
maybe "__dir__" or "__str__"? (not iterable)  [attr-defined]
            for p in paths[_level]:
                     ^~~~~~~~~~~~~
jupyterlab_server/config.py:398: error: Left operand of "and" is always true 
[redundant-expr]
            if write_config_dir is None and paths[_level]:
               ^~~~~~~~~~~~~~~~~~~~~~~~
jupyterlab_server/config.py:399: error: Value of type "object" is not indexable
 [index]
                write_config_dir = osp.join(paths[_level][0], config_name)
                                            ^~~~~~~~~~~~~~~~
```

**Comment by divyansshhh** [comment]
I think lint is fixed now.

**Review by krassowski — APPROVED** [review]
LGTM thank you @divyansshhh =!

**Comment by krassowski** [comment]
Released in https://github.com/jupyterlab/jupyterlab_server/releases/tag/v2.27.0

**Pull request merged**
