### PR TITLE
Prepare for jupyter_server preferred_dir fix

### PR DESCRIPTION
**Pull request by vidartf**
Support relocated trait in jupyter_server (https://github.com/jupyter-server/jupyter_server/pull/983).

Falls back on the old trait name if the new one is undefined or ill defined.

### CODE REVIEW

**Comment by vidartf** [comment]
I'm not sure what the CI error is about, but I'm assuming it is unrelated?

**Comment by fcollonval** [comment]
CI failures are related to https://github.com/jupyterlab/maintainer-tools/pull/138

**Comment by fcollonval** [comment]
@vidartf could you confirm this is waiting for a new release of jupyter-server?

**Comment by vidartf** [comment]
@fcollonval This was waiting for a final structure on the jupyter-server PR. Now that it has been merged, I will update this PR. After that it can be be merged and ideally released before the jupyter-server release.

**Comment by vidartf** [comment]
One of the tests that call `pytest.skip` seems to reliably be causing timeout errors on cleanup. Any thoughts on how to resolve this?

**Comment by fcollonval** [comment]
@vidartf does it raise an error if you return instead of raising skip?

**Comment by blink1073** [comment]
I just released a new version of pytest-jupyter, kicking the tests.

**Comment by blink1073** [comment]
Ugh, apparently `concurrent.futures._base.TimeoutError` is not the same as `TimeoutError`.

**Comment by blink1073** [comment]
Okay, we're good now.  The lint job failed because it couldn't yet find the new pytest-jupyter, and the macos jobs are queued due to the recent jupyterlab release.

**Review by fcollonval — APPROVED** [review]
Thanks @vidartf 

Is it okay if I merge and then release `jupyterlab_server`?

**Comment by fcollonval** [comment]
jupyterlab_server [2.18.0](https://github.com/jupyterlab/jupyterlab_server/releases/tag/v2.18.0) has been released with this feature

**Pull request merged**
