### PR TITLE
[wip] investigate potential json encoding issues with non-Latin characters

### PR DESCRIPTION
**Pull request by bollwyvl**
Now that #96 is starting to think about non-latin characters, and #102 (which this upstreams) is adding a broader test matrix, this is testing a hunch I have around non-ascii characters in schemas and settings causing issues on Windows. Would love to be proven wrong! But the fix would probably be quick (just add `encoding="utf-8"` in a few spots.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Hooray 3.5! Boo 3.8!

**Comment by bollwyvl** [comment]
Ok, looking good here, but changes rather a lot of stuff... would we prefer to break this up? There's a real bug in the previous file metadata stuff i made, in addition to the focus of this PR (the unicode stuff).

**Comment by goanpeca** [comment]
So maybe split into the windows fix on another PR and make this one the utf8 stuff only?

**Comment by bollwyvl** [comment]
The good parts of this ended up in #107 and #108, closing.

**Pull request closed without merging**
