### PR TITLE
Use json5 to load settings files.

### PR DESCRIPTION
**Pull request by ian-r-rose**
This json5 implementation seems like is works okay -- it is written by someone on the Chromium team. It has all sorts of blinking disclaimers that it is extremely slow, but I don't think we need a particularly high-performance algorithm for this use-case.

### CODE REVIEW

**Comment by blink1073** [comment]
Json5 isn't on conda-forge yet...

**Comment by ian-r-rose** [comment]
Hrm, I was hoping to avoid re-implementing...

**Comment by ian-r-rose** [comment]
This came up last week, where the server-side and client-side validators for the settings files gave different answers (particularly around ECMA identifiers-as-keys).

**Comment by blink1073** [comment]
It is fairly straightforward to get something on conda-forge.  It doesn't have any dependencies.

**Comment by blink1073** [comment]
I'm sick today, but here are the instructions: https://conda-forge.org/#add_recipe

**Comment by ian-r-rose** [comment]
`pyjson5` is now on conda-forge, and using this branch prevents 500 errors when the user tries to save valid `JSON5`-formatted settings files.

**Comment by jasongrout** [comment]
:tada:

**Pull request merged**
