### PR TITLE
LicensesManager and API/CLI

### LINKED ISSUE #160: Move WIP license reporting here from core?
Over on https://github.com/jupyterlab/jupyterlab/pull/9779 I've started some work to make frontend library license reporting more structured. The current alpha release includes a `third-party-licenses.txt`, but the baseline report is pretty simple. That PR moves the reporting to a predictable `third-party-license.json` structure (even have a schema, but got rid of it) generated by a single codepath in `@jupyterlab/builder`, and on top of it builds:

- an API endpoint `/lab/api/licenses`
- a CLI tool `jupyter lab licenses`

...with all the fixin's: different output formats, etc. 

Those things would be fine to land there, exclusively, but license compliance seems a thing that is probably even _more_ important to downstream Lab-derived applications. Also, the `federated_modules` data definitions live over here, which is a pretty important piece.

If this happened, that PR would probably split into:
- `jupyterlab/jupyterlab`
  - `@jupyterlab/builder` dev tool which generates `third-party-licenses.json`
  - `@jupyterlab/licenses-extension` which consumes the API
- `jupyterlab/jupyterlab_server`
  - the `LicensesManager` and `LicensesHandler`
- not sure
  - the `LabLicensesApp` for the CLI
    - might be nice to have here for folks to subclass

Any thoughts appreciated!

### PR DESCRIPTION
**Pull request by bollwyvl**
[![binder-badge]][binder]

[binder-badge]: https://mybinder.org/badge_logo.svg
[binder]:
  https://mybinder.org/v2/gh/bollwyvl/jupyterlab-meta/more-license-work?urlpath=lab/tree/README.md

- fixes #160
- moved from https://github.com/jupyterlab/jupyterlab/pull/9779
- relationship between the two tracked by https://github.com/bollwyvl/jupyterlab-meta/tree/more-license-work

This adds `lab/api/licenses` and the base class for `jupyter lab licenses` (to be refined by a particular application) for listing the licenses of frontend libraries included in the core (and any federated) bundles. 

The (configurable) `third-party-licenses.json` is collected by `@jupyterlab/builder`. 

This will help ensure that license compliance (for e.g. `Apache-2.0`, which requires distribution of the license text) is not hard to achieve for both core and extension developers.

### CODE REVIEW

**Comment by blink1073** [comment]
Is this ready for review?

**Comment by bollwyvl** [comment]
Thanks for checking in!

_This_ side of the house _is_ ready for review. Nothing will _happen_ until the `@jupyterlab/builder` side of the house has been updated, as there won't be any files in place, but it was useful to co-develop the features to smoke test all the bells and whistles.

**Comment by bollwyvl** [comment]
Updated this to add a `bundles` top-level key to the JSON response, but otherwise, remains ready for review.

**Comment by goanpeca** [comment]
Thanks a lot for working on this @bollwyvl  🚀

**Comment by bollwyvl** [comment]
A remaining todo on this is to add it to the openapi spec... looking into it.

**Review by blink1073 — APPROVED** [review]
Thank you!

**Pull request merged**
